{lib, ...}: let
  settings = import ../settings/keybinds.nix { inherit lib; };
  importantPrefixes = [];
  submaps = {};

  toLua = lib.generators.toLua { };

  renderArgs =
    value:
    if lib.isAttrs value && value ? _args then
      lib.concatMapStringsSep ", " toLua value._args
    else
      toLua value;

  renderSection =
    name: text:
    lib.optionalString (text != "") ''
      -- ${name}
      ${text}
    '';

  renderSettings =
    let
      names = lib.sort lib.lessThan (lib.attrNames settings);
      luaLocalNames = builtins.filter (
        name: lib.isAttrs settings.${name} && settings.${name} ? _var
      ) names;
      settingNames = builtins.filter (name: !(builtins.elem name luaLocalNames)) names;
      importantNames = lib.unique (
        lib.concatMap (
          prefix: builtins.filter (name: lib.hasPrefix prefix name) settingNames
        ) importantPrefixes
      );
      orderedNames =
        importantNames ++ builtins.filter (name: !(builtins.elem name importantNames)) settingNames;
      renderLocal =
        name:
        let
          value = settings.${name};
        in
        "local ${value.name or name} = ${renderArgs value._var}\n";
      renderCall = name: value: "hl.${name}(${renderArgs value})\n";
      renderCalls =
        name: value:
        lib.concatMapStrings (renderCall name) (if builtins.isList value then value else [ value ]);
    in
    lib.optionalString (luaLocalNames != [ ]) (
      renderSection "settings.locals" (lib.concatMapStrings renderLocal luaLocalNames)
    )
    + lib.concatMapStrings (
      name: renderSection "settings.${name}" (renderCalls name settings.${name})
    ) orderedNames;

  renderSubmaps =
    let
      renderLuaArg = value: lib.replaceStrings [ "\n" ] [ "\n  " ] (renderArgs value);
      renderCall = name: value: "  hl.${name}(${renderLuaArg value})\n";
      renderCalls =
        name: values:
        lib.concatMapStrings (renderCall name) (builtins.filter (value: !lib.isString value) values);
      renderSubmap =
        name: submap:
        renderSection "submaps.${name}" (
          "hl.define_submap(${toLua name}"
          + lib.optionalString (submap.onDispatch != "") ", ${toLua submap.onDispatch}"
          + ", function()\n"
          + lib.concatMapStrings (settingName: renderCalls settingName submap.settings.${settingName}) (
            lib.sort lib.lessThan (lib.attrNames submap.settings)
          )
          + "end)\n"
        );
      hasLuaSettings =
        submap:
        lib.any (values: builtins.any (value: !lib.isString value) values) (lib.attrValues submap.settings);
      luaSubmaps = lib.filterAttrs (_: hasLuaSettings) submaps;
      names = lib.sort lib.lessThan (lib.attrNames luaSubmaps);
    in
    lib.concatMapStrings (name: renderSubmap name luaSubmaps.${name}) names;

  hasLuaSubmaps = lib.any (
    submap:
    lib.any (values: builtins.any (value: !lib.isString value) values) (lib.attrValues submap.settings)
  ) (lib.attrValues submaps);

in 
  builtins.toFile 
    "hyprland.test.lua" 
    (''
      -- Generated by Home Manager.
      -- See https://wiki.hypr.land/Configuring/Start/

    ''
    + renderSettings
    + renderSubmaps)
